crowdfund_original/config/routes.rb
Rails.application.routes.draw do
	root "projects#index"
	# get "projects" => "projects#index"
	# get "projects/:id" => "projects#show", as: "project"
	# get "projects/:id/edit" => "projects#edit", as: "edit_project"
	# patch "projects/:id" => "projects#update"

	resources :projects
end

crowdfund_original/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

crowdfund_original/app/models/project.rb
class Project < ApplicationRecord
	def expired?
		pledging_ends_on.strftime("%Y-%m-%d") < Time.now.strftime("%Y-%m-%d")
			
	end

	def self.ordered
		where("pledging_ends_on > ?", Date.today).order("pledging_ends_on asc") 
	end
end

crowdfund_original/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

crowdfund_original/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
	def index
		@projects = Project.ordered
	end

	def show
		@project = Project.find(params[:id])
	end

	def edit
		@project = Project.find(params[:id])
	end

	def update
		@project = Project.find(params[:id])
		@project.update(project_params)
		redirect_to project_path(@project)
	end

	def new
		@project = Project.new
	end

	def create			
		@project = Project.new(project_params)

		@project.save
		redirect_to project_path(@project)
	end

	def destroy
		@project = Project.find(params[:id])
		@project.destroy
		redirect_to projects_path
	end
end


private 
	def project_params
		params.require(:project).
			permit(:name, :description, :target_pledge_amount, :website, :pledging_ends_on, :team_members, :image_file_name)
	end

crowdfund_original/app/helpers/application_helper.rb
module ApplicationHelper
end

crowdfund_original/app/helpers/projects_helper.rb
module ProjectsHelper
	def time_remaining(project)
		if project.expired?
			content_tag(:strong, "Project has expired!")
		else
			today = Time.now.strftime("%Y-%m-%d")
			end_date = project.pledging_ends_on		
			distance_of_time_in_words(end_date, today)
		end
	end

	def image_for(project)
		if project.image_file_name.blank?
			image_tag("placeholder.jpg", width: "100px")
		else
			image_tag(project.image_file_name, width: "100px")
		end
	end
end

crowdfund_original/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Crowdfund</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

crowdfund_original/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
		<p>
			<%= f.label :name  %> <br/>
			<%= f.text_field :name, autofocus: true %> 
		</p>
		<p>
			<%= f.label :website  %> <br/>
			<%= f.text_field :website %> 
		</p>
		<p>
			<%=  f.label :description %><br/>
			<%= f.text_area :description, cols:40, rows: 7 %>
		</p>
		<p>
			<%=  f.label :target_pledge_amount %> ($)<br/>
			<%= f.number_field :target_pledge_amount  %>
		</p>
		<p>
			
			<%=  f.label :pledging_ends_on %><br/>
			<%= f.date_field :pledging_ends_on  %>
		</p>
		<p>
			
			<%=  f.label :image_file_name %><br/>
			<%= f.text_field :image_file_name  %>
		</p>
		<p>
			
			<%=  f.label :team_members %><br/>
			<%= f.text_field :team_members %>
		</p>
		<p>
			<%= f.submit  %> |
			<%= link_to("Cancel",projects_path)  %>
		</p>
    <% end %>

crowdfund_original/app/views/projects/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Edit Project</title>
</head>
<body>
	<h1>Editing <%= @project.name %></h1>
	<%= render 'form'  %>
</body>
</html>

crowdfund_original/app/views/projects/index.html.erb
<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Projects</title>
	</head>
	<body>
		<h1><%= pluralize(@projects.size, "Project") %></h1>
		<%= link_to("Add new project", new_project_path)  %>
		<% @projects.each do |project| %>
			<article>
				<header>
					<h2><%= link_to(project.name, project) %></h2>
					<%= image_for(project) %>
				</header>
				<table>
					<tr>
						<th>description:</th>
						<td><%= truncate(project.description, length: 150) %></td>
					</tr>
					<tr>
						<th>Target:</th>
						<td><%= number_to_currency(project.target_pledge_amount) %></td>
					</tr>
					<tr>
						<th>Website</th>
						<td><%= project.website %></td>
					</tr>
					<tr>
						<th>End Date</th>
						<td><%= project.pledging_ends_on %> (<%= time_remaining(project) %> remaining)</td>
					</tr>
				</table>
			</article>
		<% end %>							
	</body>
</html>

crowdfund_original/app/views/projects/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Projects</title>
</head>
<body>
	<h1>Add a new project</h1>
	<%= render 'form'  %>
</body>
</html>

crowdfund_original/app/views/projects/show.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Individual Project description</title>
	</head>
	<body>
		<article>
			<header>
				<h2><%= @project.name %></h2>
				<%= image_for(@project)  %>
			</header>
			<table>
				<tr>
					<th>description:</th>
					<td><%= @project.description %></td>
				</tr>
				<tr>
					<th>Target:</th>
					<td><%= number_to_currency(@project.target_pledge_amount) %></td>
				</tr>
				<tr>
					<th>Website</th>
					<td><%= @project.website %></td>
				</tr>
				<tr>
					<th>Team Members</th>
					<td><%= @project.team_members %></td>
				</tr>
				<tr>
					<th>End Date</th>
					<td><%= @project.pledging_ends_on %> (<%= time_remaining(@project) %> remaining)</td>
				</tr>
			</table>
		</article>
		<%= link_to("All Projects", root_path) %>|
		<%= link_to("Edit", edit_project_path) %>
		<%= link_to "Delete", project_path(@project), method: :delete, data: {confirm: 'Are you sure? '}  %>
	</body>
</html>